### ISSUE TITLE
Inside howto flow, if user is doing another action

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#358]
-> allow this action and when ended bring back user to previous state instead of default.

UPDATE:
Seem to not be working see image below 
<img width="915" alt="Screen Shot 2022-12-05 at 15 17 12" src="https://user-images.githubusercontent.com/25544824/205646610-6cb7a01f-0740-40bc-a42d-5cb33dfd0a56.png">

**Comment by JerryVDP** [comment]
By design.

If user answers with an unexpected answer (in this case "test" instead of Transcribe\Reminders\Other Skills) and the user is boarded, then Fredo will set the user state to be back to his platform's default and send his test to the default board.

**Comment by JerryVDP** [comment]
Fixed for Transcribe

**Comment by assafza** [comment]
@JerryVDP  It still not working. I remember we discussed about it in a concept of goind back to the previous state no?
[Screenshot 2022-12-26 at 14 46 54](https://user-images.githubusercontent.com/25544824/209550659-2a01ef88-8076-4c12-80b4-641e966a3556.png)

**Comment by JerryVDP** [comment]
No, this is by design as we discussed.
You sent "test" to Fredo, which broke the current flow and changed the user state back to his connected platform.

What I fixed is:
if a user clicks on "Transcribe" button (without sending any message, such as "test"), and tries to transcribe a message, then after a successful transcription the user state is back to Howto.

**Comment by assafza** [comment]
Ok make sense.
